services:
  sidecar:
    build:
      context: ./test-induction-api
    image: test-induction-api:latest
    ports:
      - "8080:8080"

  ui:
    build:
      context: ./test-induction-ui
    image: test-induction-ui:latest
    ports:
      - "8090:8090"
    environment:
      INDUCTION_API_BASEURL: http://sidecar:8080
    depends_on:
      sidecar:
        condition: service_healthy

  sample-app:
    build:
      context: ./sample-app
    image: sample-app:latest
    ports:
      - "9090:9090"
    environment:
      INDUCTION_SIDECARHOST: sidecar
      INDUCTION_SIDECARPORT: "8080"
    depends_on:
      sidecar:
        condition: service_healthy
